# Generated by Django 2.2.7 on 2020-03-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currecy',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
